name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: ['2.7', '3.6', '3.7', '3.8','3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v2

    # Special handling for Python 2.7
    - name: Set up Python 2.7 and pip (+ install dependencies)
      if: matrix.python-version == '2.7'
      run: |
        sudo apt-get update
        sudo apt-get install -y python2.7 python-pip
        python2.7 -m pip install --upgrade "pip<21.0" "setuptools<45"
        python2.7 -m pip install tox==3.24.4 tox-gh-actions

    - name: Set up Python ${{ matrix.python-version }}
      if: matrix.python-version != '2.7'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key:
          ${{ matrix.python-version }}-v1-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ matrix.python-version }}-v1-

    - name: Install dependencies for Python 3.x
      if: matrix.python-version != '2.7'
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade tox tox-gh-actions

    - name: Tox tests
      run: |
        tox -v

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        name: Python ${{ matrix.python-version }}
